### ISSUE TITLE
IQAudioRecorderViewController.h file not found

### ISSUE THREAD

**Issue by abarmawi** [relatedcode/FirebaseChat#125]
i have downloaded the project, but i got this error when i build it.

IQAudioRecorderViewController.h file not found.

any help??

**Comment by relatedcode** [comment]
@abarmawi Run 'pod update' in CocoaPods.

**Comment by abarmawi** [comment]
@relatedcode 
i did pod update then pod install, but issue still appears..

**Comment by moh1122** [comment]
wht is the diff between pod install and pod update

**Comment by relatedcode** [comment]
@abarmawi Ok. If you have the latest code from my repo and you have run the 'pod install' and 'pod update', then it should work. But you must have the latest (1.6) version from me.

**Comment by relatedcode** [comment]
@moh1122 You should run both 'pod install' and 'pod update'. One after the other. Just for sure. For more info you can check CocoaPods site.

**Comment by abarmawi** [comment]
@relatedcode 

thanks, it works fine.

**Comment by relatedcode** [comment]
@abarmawi Great news!
